[package]
name = "openloops-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
openloops-application = { path = "../openloops-application" }
openloops-domain = { path = "../openloops-domain" }

[lints]
workspace = true
