[CmdletBinding()]
param(
    [string]$ManifestPath = 'contracts/synchronization/mail-sync-boundary.json',
    [string]$AdrPath = 'docs/adr/ADR-004-synchronization.md',
    [string]$TraceabilityPath = 'docs/prd-traceability.md',
    [string]$GovernancePath = 'contracts/governance/capabilities.json',
    [string]$PermissionPath = 'contracts/identity/permission-boundary.json',
    [string]$AuthenticationPath = 'contracts/identity/authentication-boundary.json',
    [string]$PrivacyPath = 'contracts/privacy/persistence-boundary.json',
    [string]$SupportPath = 'contracts/support/support-matrix.json',
    [string]$BuildPath = 'contracts/build-skeleton/skeleton.json',
    [switch]$Quiet
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (& git rev-parse --show-toplevel 2>$null).Trim()
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($repoRoot)) { throw 'Run inside the repository.' }
function Resolve-Input([string]$Path) { if ([IO.Path]::IsPathRooted($Path)) { return [IO.Path]::GetFullPath($Path) }; [IO.Path]::GetFullPath((Join-Path $repoRoot $Path)) }
function Fail([string]$Id) { if (-not $script:failureSet.ContainsKey($Id)) { $script:failureSet[$Id]=$true; $script:failures.Add($Id) } }
function Exact([object[]]$Actual,[object[]]$Expected,[string]$Id) { $a=@($Actual|ForEach-Object{[string]$_});$e=@($Expected|ForEach-Object{[string]$_});$au=@($a|Sort-Object -Unique);$eu=@($e|Sort-Object -Unique);if($a.Count-ne$au.Count-or$au.Count-ne$eu.Count-or(Compare-Object $eu $au)){Fail $Id} }
function Empty([object[]]$Values,[string]$Id) { if (@($Values).Count -ne 0) { Fail $Id } }
$script:failures=[Collections.Generic.List[string]]::new();$script:failureSet=@{}
$expectedHash='5f0786ec179f1d30101803d4f1dda963b8c7cb6505a3bd4e3c56df242a7b9462'
$expectedChecks=@('P0-SYNC-INVENTORY-001','P0-SYNC-CHECKPOINT-001','P0-SYNC-DELTA-001','P0-SYNC-ELIGIBILITY-001','P0-SYNC-TRANSACTION-001','P0-SYNC-RESILIENCE-001','P0-SYNC-COVERAGE-001','P0-SYNC-REPLAY-001','P0-SYNC-SCHEDULING-001','P0-SYNC-CROSS-CONTRACT-001','P0-SYNC-CLAIMS-001','P0-SYNC-FRESH-CHECKER-001')
$expectedRequirements=@('OL-GOV-001','OL-AUTH-004','OL-SYNC-001','OL-SYNC-002','OL-SYNC-003','OL-SYNC-004','OL-SYNC-005','OL-SYNC-006','OL-SYNC-007','OL-SYNC-008','OL-SYNC-009','OL-SYNC-010','OL-SYNC-011','OL-SYNC-012','OL-SYNC-013','OL-NFR-001','OL-NFR-003','OL-NFR-004','OL-NFR-005','OL-NFR-007','OL-NFR-012')
try { $m=Get-Content -Raw -LiteralPath (Resolve-Input $ManifestPath)|ConvertFrom-Json; $canonical=$m|ConvertTo-Json -Depth 100 -Compress; $hash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($canonical))).ToLowerInvariant(); if($hash-ne$expectedHash){Fail 'P0-SYNC-INVENTORY-001'} } catch { [Console]::Error.WriteLine('BLOCKED: P0-SYNC-INVENTORY-001 manifest parse failed.'); exit 1 }
if($m.schema_version-ne1-or$m.work_item-ne'P0-WI-07'-or$m.adr-ne'ADR-004'-or$m.decision_status-ne'accepted_contract_runtime_unimplemented'){Fail 'P0-SYNC-INVENTORY-001'}
Exact @($m.owner_decisions) @('OWN-05','OWN-09') 'P0-SYNC-INVENTORY-001'; Exact @($m.requirements) $expectedRequirements 'P0-SYNC-INVENTORY-001'
Exact @($m.collection_contracts.id) @('SYNC-MAIL-FOLDER-001','SYNC-REMINDER-COLLECTION-001','SYNC-CALENDAR-COLLECTION-001') 'P0-SYNC-INVENTORY-001'
foreach($row in $m.collection_contracts){if($row.state-ne'disabled'-or$row.advertised-ne$false-or@($row.gates).Count-eq0){Fail 'P0-SYNC-INVENTORY-001'}}
Exact @($m.checkpoint_contract.fields) @('record_id','account_ref','collection_locator','delta_or_next_locator','query_fingerprint_hmac','collection_kind','status_code','last_complete_at') 'P0-SYNC-CHECKPOINT-001'
foreach($phrase in @('one independent record per bound account and selected collection','opaque encrypted full nextLink or deltaLink','never parse for business data reconstruct edit append export or reuse across a binding')){if(($m.checkpoint_contract|ConvertTo-Json -Compress)-notmatch[regex]::Escape($phrase)){Fail 'P0-SYNC-CHECKPOINT-001'}}
if($m.checkpoint_contract.retention-ne'checkpoint_until_scope_removed'-or$m.checkpoint_contract.deletion-ne'delete_local_only'-or$m.checkpoint_contract.reset-ne'scope_removal_or_disconnect'){Fail 'P0-SYNC-CHECKPOINT-001'}
if($m.checkpoint_contract.binding-ne'account_ref collection_locator endpoint API version exact selected fields initial window or filter immutable-id preference schema version and policy version'-or$m.checkpoint_contract.binding_drift-ne'delete only the affected checkpoint and require visible bounded rebaseline'){Fail 'P0-SYNC-CHECKPOINT-001'}
if($m.poll_policy.mode-ne'per_folder_delta_plus_periodic_bounded_reconciliation'-or$m.poll_policy.webhooks-ne'prohibited_for_mvp'-or$m.delta_protocol.at_least_once-ne$true-or$m.delta_protocol.ordering_assumption-ne'none across pages retries or reconciliation'-or$m.delta_protocol.cursor_logging-ne'prohibited'-or$m.delta_protocol.plaintext_cursor_persistence-ne'prohibited'-or$m.cycle_budgets.status-ne'finite exact values pending measured G-MAIL experiments'){Fail 'P0-SYNC-DELTA-001'}
if($m.delta_protocol.completion-ne'deltaLink marks a completed round only after every page item has a durable safe outcome; last_complete_at updates only at that committed deltaLink'-or$m.delta_protocol.cursor_invalid-ne'mark resync visible; discard only the affected checkpoint; bounded review-only rescan the same selected folder and history window'-or$m.delta_protocol.cursor_invalid_trigger-ne'exact status and error signature pending G-MAIL; all other auth account scope folder and query errors fail closed without resync'-or$m.delta_protocol.tombstones-ne'process as source availability change; never infer loop closure or Microsoft artifact deletion'-or$m.delta_protocol.initial_query-ne'ADR-006 defines the selected-field and immutable-id request contract; execution remains blocked on G-MAIL'){Fail 'P0-SYNC-DELTA-001'}
if($m.eligibility_policy.initial_or_backfill.incoming_already_read-ne'analyze into one noninterruptive history-review batch'-or$m.eligibility_policy.initial_or_backfill.incoming_unread-ne'record the unread observation and wait for a later read observation after the baseline'-or$m.eligibility_policy.initial_or_backfill.saved_sent_copy-ne'analyze into the history-review batch'-or$m.eligibility_policy.initial_or_backfill.automatic_mutation-ne'prohibited'-or$m.eligibility_policy.post_baseline_incoming.observed_unread_then_read-ne'analyze once when the later observation establishes unread-to-read'-or$m.eligibility_policy.post_baseline_incoming.first_observed_already_read-ne'analyze once with first-observation marker because polling may have coalesced states'-or$m.eligibility_policy.post_baseline_incoming.first_observed_unread-ne'wait for a later read observation'-or$m.eligibility_policy.post_baseline_incoming.isRead_meaning-ne'trigger only; never evidence of careful review'-or$m.eligibility_policy.post_baseline_outgoing.saved_sent_copy_first_observed-ne'analyze once'-or$m.eligibility_policy.post_baseline_outgoing.draft_or_compose-ne'never activates a loop'-or$m.eligibility_policy.post_baseline_outgoing.claim_language-ne'sent copy observed; never delivered'-or$m.eligibility_policy.idempotency-ne'purpose-separated keyed digest of bound account tested locator observed version and policy version'){Fail 'P0-SYNC-ELIGIBILITY-001'}
Exact @($m.page_transaction.durable_safe_outcomes) @('no_candidate','needs_review','processed','source_unavailable','recoverable_quarantine') 'P0-SYNC-TRANSACTION-001'; Exact @($m.page_transaction.nonterminal_outcomes) @('queued','retry_scheduled','ambiguous_write','failed_without_recoverability') 'P0-SYNC-TRANSACTION-001'
Exact @($m.page_transaction.steps) @('stage encrypted continuation and keyed source-version observation keys','deduplicate every item within the bound account collection and policy version','apply eligibility without treating isRead or sent-copy observation as proof of review or delivery','fetch only the exact G-MAIL and ADR-006 field contract transiently','persist only an ADR-PRIV-001-approved safe outcome or recoverable quarantine record','atomically commit page outcomes before replacing the durable collection checkpoint') 'P0-SYNC-TRANSACTION-001'
if($m.page_transaction.cursor_advance_rule-ne'prohibited until every page item is durable and safe'-or$m.page_transaction.crash_rule-ne'a crash before atomic commit replays the page; source-version idempotency prevents duplicate transitions or mutations'-or$m.page_transaction.whole_page_failure-ne'transport parse or schema failure blocks checkpoint replacement because no safe per-item disposition exists'){Fail 'P0-SYNC-TRANSACTION-001'}
if($m.retry_policy.retry_after-ne'honor a valid Graph Retry-After and make no request before it expires'-or$m.retry_policy.missing_or_invalid_retry_after-notmatch'bounded exponential backoff with positive jitter'-or$m.retry_policy.raw_error_url_header_body_logging-ne'prohibited'-or$m.quarantine_policy.before_cursor_advance-notmatch'keep the cursor blocked'-or$m.quarantine_policy.failed_bounded_without_recoverability-ne'prohibited_terminal_outcome'-or$m.quarantine_policy.resolution_cleanup-ne'retry success dismissal or recovery atomically deletes the related job_health record before returning message_observation to ordinary retention; no quarantine_ref may dangle'-or$m.quarantine_policy.disconnect_cleanup-ne'atomically delete local message_observation and related job_health regardless of age; zero Graph mutation'){Fail 'P0-SYNC-RESILIENCE-001'}
Exact @($m.retry_policy.retryable_classes) @('http_429','http_503','http_504','timeout','connection_interrupted') 'P0-SYNC-RESILIENCE-001';Exact @($m.retry_policy.nonretryable_classes) @('permission_denied','account_mismatch','invalid_request_contract','unsupported_cloud','host_or_origin_mismatch') 'P0-SYNC-RESILIENCE-001'
Exact @($m.quarantine_policy.approved_fields) @('record_id','account_ref','source_version_hmac','observed_version_hmac','quarantined_locator','direction_code','read_observation_code','first_observation_code','job_outcome_code','failure_class','retry_state','policy_version','retry_generation','observed_at') 'P0-SYNC-RESILIENCE-001'
if($m.reconciliation_policy.completeness_claim-ne'prohibited'-or$m.reconciliation_policy.folder_rename-notmatch'do not infer identity from a display name'-or$m.reconciliation_policy.folder_missing_or_deleted-notmatch'delete its application-owned checkpoint'){Fail 'P0-SYNC-COVERAGE-001'}
Exact @($m.reconciliation_policy.known_unrecoverable) @('an item that enters is read and leaves selected scope between observations','a sent copy not saved or moved or deleted before observation','send-as on-behalf-of and alternate sent-folder behavior not proven by G-MAIL','time outside the configured history window') 'P0-SYNC-COVERAGE-001'
if($m.replay_policy.automatic_reminders-ne'prohibited'-or$m.replay_policy.silent_retroactive_mutation-ne'prohibited'-or$m.replay_policy.presentation-ne'newly detected historical results enter a review batch'){Fail 'P0-SYNC-REPLAY-001'}
Exact @($m.replay_policy.triggers) @('provider_change','parser_change','policy_change','identity_change','folder_change','quarantine_retry','analysis_unavailable_recovery') 'P0-SYNC-REPLAY-001'
if($m.poll_policy.cadence_seconds.default-ne60-or$m.poll_policy.cadence_seconds.minimum-ne60-or$m.poll_policy.cadence_seconds.maximum-ne900-or$m.poll_policy.single_flight-ne'exactly one active poll or reconciliation job per account and collection'-or$m.poll_policy.cadence_status-notmatch'internal validation target'-or$m.poll_policy.background_boundary-notmatch'no coverage claim while stopped sleeping signed out offline'){Fail 'P0-SYNC-SCHEDULING-001'}
foreach($name in @('graph_calls','network_contacts','configured_accounts','configured_collections','checkpoints_persisted','gates_passed','acceptance_criteria_completed','capabilities_enabled','capabilities_advertised','supported_rows')){Empty @($m.claims.$name) 'P0-SYNC-CLAIMS-001'}
if($m.runtime_boundary.status-ne'unimplemented'-or$m.runtime_boundary.graph_transport-ne$false-or$m.runtime_boundary.scheduler-ne$false-or$m.runtime_boundary.durable_state-ne$false-or$m.runtime_boundary.addin_authority-ne$false){Fail 'P0-SYNC-CLAIMS-001'}
foreach($name in @('selected_dependencies','network_origins','accepted_secrets')){Empty @($m.runtime_boundary.$name) 'P0-SYNC-CLAIMS-001'}
$g=Get-Content -Raw -LiteralPath (Resolve-Input $GovernancePath)|ConvertFrom-Json;$a4=@($g.adrs|Where-Object id -eq 'ADR-004');if($a4.Count-ne1-or$a4[0].status-ne'accepted'-or@($g.gates|Where-Object status -ne 'unrun').Count-ne0-or@($g.capabilities|Where-Object{$_.state-ne'disabled'-or$_.advertised-ne$false}).Count-ne0-or@($g.product_acceptance_criteria_completed).Count-ne0){Fail 'P0-SYNC-CROSS-CONTRACT-001';Fail 'P0-SYNC-CLAIMS-001'}
$ownerExpected=[ordered]@{'OWN-05'=@{adrs=@('ADR-004','ADR-006','ADR-009');gates=@('G-CAL','G-MAIL')};'OWN-09'=@{adrs=@('ADR-004');gates=@('G-MAIL')}};foreach($ownerId in $ownerExpected.Keys){$o=@($g.owner_decisions|Where-Object id -eq $ownerId);if($o.Count-ne1-or$o[0].status-notlike'accepted*'){Fail 'P0-SYNC-CROSS-CONTRACT-001';continue};Exact @($o[0].adrs) @($ownerExpected[$ownerId].adrs) 'P0-SYNC-CROSS-CONTRACT-001';Exact @($o[0].gates) @($ownerExpected[$ownerId].gates) 'P0-SYNC-CROSS-CONTRACT-001'}
$flow=@($g.threat_flows|Where-Object id -eq 'graph_mail_content');if($flow.Count-ne1-or$flow[0].prohibited_behavior-ne'no real content in fixtures, logs, or state; no unbounded fetch or complete-event-observation claim'){Fail 'P0-SYNC-CROSS-CONTRACT-001'}else{Exact @($flow[0].adrs) @('ADR-003','ADR-004','ADR-006') 'P0-SYNC-CROSS-CONTRACT-001';Exact @($flow[0].gates) @('G-MAIL','G-PRIV') 'P0-SYNC-CROSS-CONTRACT-001'}
$p=Get-Content -Raw -LiteralPath (Resolve-Input $PermissionPath)|ConvertFrom-Json;$mail=@($p.permission_rows|Where-Object id -eq 'PERM-MAIL-DETECT-001');if($mail.Count-ne1-or$mail[0].state-ne'disabled'-or$p.mail_folder_policy.automatic_expansion-ne'prohibited'-or$p.mail_folder_policy.shared_or_delegated_folders-ne'prohibited'){Fail 'P0-SYNC-CROSS-CONTRACT-001'}
$auth=Get-Content -Raw -LiteralPath (Resolve-Input $AuthenticationPath)|ConvertFrom-Json;if($auth.flow.runtime_status-ne'unimplemented'-or@($auth.claims.network_contacts).Count-ne0){Fail 'P0-SYNC-CROSS-CONTRACT-001'}
$priv=Get-Content -Raw -LiteralPath (Resolve-Input $PrivacyPath)|ConvertFrom-Json;$cp=@($priv.record_types|Where-Object id -eq 'sync_checkpoint');$obs=@($priv.record_types|Where-Object id -eq 'message_observation');$health=@($priv.record_types|Where-Object id -eq 'job_health');$ql=@($priv.lifecycle_transitions|Where-Object id -eq 'quarantine_retention');if($cp.Count-ne1-or$obs.Count-ne1-or$health.Count-ne1-or$ql.Count-ne1){Fail 'P0-SYNC-CROSS-CONTRACT-001'}else{Exact @($ql[0].record_types) @('message_observation') 'P0-SYNC-CROSS-CONTRACT-001';if($ql[0].states.Count-ne2-or$ql[0].states[0].when-ne'recoverable_quarantine_unresolved'-or$ql[0].states[0].retention-ne'unresolved_quarantine'-or$ql[0].states[1].when-ne'retry_succeeded_dismissed_or_recovery_complete'-or$ql[0].states[1].retention-ne'observation_window_plus_15'){Fail 'P0-SYNC-CROSS-CONTRACT-001'}}
$privacyFields=@($cp[0].field_groups.fields)+@($obs[0].field_groups.fields)+@($health[0].field_groups.fields);foreach($field in @('delta_or_next_locator','query_fingerprint_hmac','quarantined_locator','retry_generation','error_class_code','stale_since')){if($privacyFields-notcontains$field){Fail 'P0-SYNC-CROSS-CONTRACT-001'}}
$observationFields=@($obs[0].field_groups|ForEach-Object{@($_.fields)});Exact @($m.quarantine_policy.approved_fields) $observationFields 'P0-SYNC-CROSS-CONTRACT-001'
if($m.separate_decisions.permissions_and_folder_selection-ne'ADR-003'-or$m.separate_decisions.encryption_and_transaction_implementation-ne'ADR-005'-or$m.separate_decisions.message_identity_exact_fields_and_anchors-ne'ADR-006'-or$m.separate_decisions.reminder_mutation_and_reconciliation-ne'ADR-009 and ADR-011'-or$m.separate_decisions.calendar_invitation_correlation-ne'ADR-006 ADR-009 and G-CAL'){Fail 'P0-SYNC-CROSS-CONTRACT-001'}
$support=Get-Content -Raw -LiteralPath (Resolve-Input $SupportPath)|ConvertFrom-Json;if(@($support.claim_state.supported_rows).Count-ne0){Fail 'P0-SYNC-CROSS-CONTRACT-001'}
$build=Get-Content -Raw -LiteralPath (Resolve-Input $BuildPath)|ConvertFrom-Json;if($build.runtime_boundary.graph_transport-ne$false-or$build.runtime_boundary.durable_state-ne$false-or@($build.runtime_boundary.network_origins).Count-ne0-or@($build.runtime_boundary.accepted_secrets).Count-ne0){Fail 'P0-SYNC-CROSS-CONTRACT-001';Fail 'P0-SYNC-CLAIMS-001'}
$cargo=@(Get-ChildItem -LiteralPath $repoRoot -Filter Cargo.toml -Recurse -File|Where-Object{$_.FullName-notmatch'[\\/]target[\\/]'});$src=@(Get-ChildItem -LiteralPath (Join-Path $repoRoot 'crates') -Recurse -File -Include *.rs);if(Select-String -LiteralPath @($cargo.FullName) -Pattern '(?i)\b(reqwest|oauth2|hyper|ureq|tokio)\b' -Quiet){Fail 'P0-SYNC-CROSS-CONTRACT-001'};if(Select-String -LiteralPath @($src.FullName) -Pattern '(?i)\b(TcpStream|HttpClient)\b' -Quiet){Fail 'P0-SYNC-CROSS-CONTRACT-001'}
$trace=Get-Content -Raw -LiteralPath (Resolve-Input $TraceabilityPath);$traceIds=@([regex]::Matches($trace,'(?m)^\| (P0-SYNC-[A-Z-]+-001) \|')|ForEach-Object{$_.Groups[1].Value});Exact $traceIds $expectedChecks 'P0-SYNC-INVENTORY-001'
$adr=(Get-Content -Raw -LiteralPath (Resolve-Input $AdrPath))-replace'\s+',' ';foreach($phrase in @('Status:** Accepted','P0-WI-07','Owner decisions:** OWN-05, OWN-09','exactly these twelve checks','last_complete_at','deleted immediately if that window elapsed','Disconnect atomically deletes both local records regardless of age with zero Graph mutation','No gate, capability, support row, or acceptance criterion advances')){if($adr-notmatch[regex]::Escape($phrase)){Fail 'P0-SYNC-CROSS-CONTRACT-001'}}
if($failures.Count-gt0){[Console]::Error.WriteLine("BLOCKED: synchronization checks failed: $($failures -join ', ')");exit 1};if(-not$Quiet){Write-Host 'OpenLoops synchronization checks passed (12 P0-WI-07 assertions; runtime and all gates remain inactive).'}
