[CmdletBinding()]
param(
 [string]$ManifestPath='contracts/reminder/adapter-boundary.json',
 [string]$AdrPath='docs/adr/ADR-009-reminder-adapters.md',
 [string]$ThreatPath='docs/threat-model/reminder-adapter-boundary.md',
 [string]$TraceabilityPath='docs/prd-traceability.md',
 [string]$ProductSpecPath='docs/product-spec.md',
 [string]$ImplementationPlanPath='docs/implementation-plan.md',
 [string]$GovernancePath='contracts/governance/capabilities.json',
 [string]$PermissionPath='contracts/identity/permission-boundary.json',
 [string]$PrivacyPath='contracts/privacy/persistence-boundary.json',
 [string]$PersistencePath='contracts/persistence/protected-state-boundary.json',
 [string]$EvidencePath='contracts/evidence/identity-boundary.json',
 [string]$PolicyPath='contracts/domain/policy-state-boundary.json',
 [string]$SyncPath='contracts/synchronization/mail-sync-boundary.json',
 [string]$SupportPath='contracts/support/support-matrix.json',
 [string]$BuildPath='contracts/build-skeleton/skeleton.json',
 [switch]$Quiet
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repoRoot=(& git rev-parse --show-toplevel 2>$null).Trim();if($LASTEXITCODE-ne 0-or[string]::IsNullOrWhiteSpace($repoRoot)){throw'Run inside the repository.'}
function Resolve-Input([string]$p){if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path $repoRoot $p))}}
function Fail([string]$id){if(-not$script:seen.ContainsKey($id)){$script:seen[$id]=$true;$script:fail.Add($id)}}
function Json([string]$p,[string]$id){try{Get-Content -Raw -LiteralPath (Resolve-Input $p)|ConvertFrom-Json -Depth 100}catch{Fail $id;$null}}
function Text([string]$p,[string]$id){try{Get-Content -Raw -LiteralPath (Resolve-Input $p)}catch{Fail $id;''}}
function Exact([object[]]$a,[object[]]$e,[string]$id){$aa=@($a|ForEach-Object{[string]$_});$ee=@($e|ForEach-Object{[string]$_});$au=@($aa|Sort-Object -Unique);$eu=@($ee|Sort-Object -Unique);if($aa.Count-ne$au.Count-or$au.Count-ne$eu.Count-or(Compare-Object $eu $au)){Fail $id}}
function Ordered([object[]]$a,[object[]]$e,[string]$id){$aa=@($a|ForEach-Object{[string]$_});$ee=@($e|ForEach-Object{[string]$_});if($aa.Count-ne$ee.Count){Fail $id;return};for($i=0;$i-lt$ee.Count;$i++){if($aa[$i]-cne$ee[$i]){Fail $id;return}}}
function Empty([object[]]$v,[string]$id){if(@($v).Count-ne 0){Fail $id}}
function Has([string]$t,[string[]]$p,[string]$id){foreach($x in $p){if($t-notmatch[regex]::Escape($x)){Fail $id}}}
function NHash([string]$t){$c=(($t-replace"`r`n","`n").TrimEnd()+"`n");[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($c))).ToLowerInvariant()}
$script:fail=[Collections.Generic.List[string]]::new();$script:seen=@{}
$checks=@('P0-REMINDER-INVENTORY-001','P0-REMINDER-SCHEMA-001','P0-REMINDER-CATALOGS-001','P0-REMINDER-TODO-BASELINE-001','P0-REMINDER-OPERATION-PROTOCOL-001','P0-REMINDER-AMBIGUOUS-WRITE-001','P0-REMINDER-OWNERSHIP-001','P0-REMINDER-DIRECT-EDIT-001','P0-REMINDER-CONFLICT-001','P0-REMINDER-MANUAL-SOURCE-001','P0-REMINDER-CALENDAR-SAFETY-001','P0-REMINDER-REVIEW-LINK-001','P0-REMINDER-PRIVACY-001','P0-REMINDER-DEFERRED-001','P0-REMINDER-CROSS-CONTRACT-001','P0-REMINDER-CLAIMS-001','P0-REMINDER-FRESH-CHECKER-001')
$m=Json $ManifestPath 'P0-REMINDER-INVENTORY-001';if($null-eq$m){[Console]::Error.WriteLine('BLOCKED: reminder manifest parse failed.');exit 1}
$canonical=$m|ConvertTo-Json -Depth 100 -Compress;$hash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($canonical))).ToLowerInvariant()
if($hash-ne'9643f9ddcdb91bcd32c345fbea101364d21e4f663676fee0a7ef2c4a89065eb6'){Fail 'P0-REMINDER-INVENTORY-001'}
if($m.schema_version-ne 1-or$m.work_item-ne'P0-WI-12'-or$m.adr-ne'ADR-009'-or$m.decision_status-ne'accepted_contract_runtime_unimplemented'-or$m.snapshot_date-ne'2026-07-21'){Fail 'P0-REMINDER-INVENTORY-001'}
Ordered @($m.owner_decisions) @('OWN-03','OWN-04','OWN-05','OWN-07') 'P0-REMINDER-INVENTORY-001'
Ordered @($m.owned_requirements) @('OL-GOV-001','OL-REM-001','OL-REM-002','OL-REM-003','OL-REM-004','OL-REM-005','OL-REM-006','OL-REM-007','OL-REM-008','OL-REM-009','OL-REM-011','OL-REM-012','OL-REM-013','OL-REM-014','OL-REM-015','OL-REM-016') 'P0-REMINDER-INVENTORY-001'
Ordered @($m.consumed_requirements) @('OL-AUTH-003','OL-AUTH-004','OL-AUTH-005','OL-SYNC-001','OL-SYNC-006','OL-SYNC-007','OL-SYNC-012','OL-INV-002','OL-INV-004','OL-INV-005','OL-INV-006','OL-CLOSE-003','OL-CLOSE-004','OL-CLOSE-006','OL-REM-010','OL-REM-017','OL-UX-001','OL-UX-002','OL-UX-009','OL-UX-010','OL-NFR-004','OL-NFR-005','OL-NFR-006','OL-NFR-007','OL-NFR-012') 'P0-REMINDER-INVENTORY-001'
Ordered @($m.primary_acceptance_criteria) @('AC-05c','AC-10') 'P0-REMINDER-INVENTORY-001';Ordered @($m.dependent_acceptance_criteria) @('AC-12','AC-15','AC-17','AC-24') 'P0-REMINDER-INVENTORY-001'
Ordered @($m.primary_scenarios) @('AS-07','AS-11','AS-15') 'P0-REMINDER-INVENTORY-001';Ordered @($m.scenario_dependencies.id) @('AS-02','AS-10','AS-14','AS-17','AS-19','AS-21','AS-23') 'P0-REMINDER-INVENTORY-001';if(@($m.scenario_dependencies|Where-Object{$_.status -notlike 'unpassed_*'}).Count-ne 0){Fail 'P0-REMINDER-INVENTORY-001'}
Ordered @($m.blocking_gates) @('G-ID','G-MAIL','G-TODO','G-CAL','G-ADDIN','G-STATE','G-PRIV','G-AUTO','G-AUTO-FULL','G-SEC-AUDIT','G-RELEASE') 'P0-REMINDER-INVENTORY-001'
Ordered @($m.input_authorities.owner) @('ADR-003','ADR-004','ADR-005','ADR-006','ADR-008','ADR-PRIV-001') 'P0-REMINDER-DEFERRED-001'
Ordered @($m.sources.id) @('SRC-SPEC-MANUAL','SRC-SPEC-REMINDER','SRC-SPEC-DIRECT','SRC-SPEC-GATES','SRC-PLAN-OP','SRC-PLAN-ADR','SRC-RESEARCH-CONNECTION','SRC-RESEARCH-SECURITY','SRC-RESEARCH-VALIDATION','SRC-OWNERS') 'P0-REMINDER-INVENTORY-001'

$records=@($m.record_contracts);Ordered @($records.id) @('reminder_link','operation_ledger','user_authored_artifact_ref') 'P0-REMINDER-SCHEMA-001'
$privacy=Json $PrivacyPath 'P0-REMINDER-CROSS-CONTRACT-001'
foreach($r in $records){if($r.unknown_fields-ne'reject'){Fail 'P0-REMINDER-SCHEMA-001'};$pr=@($privacy.record_types|Where-Object{$_.id -eq $r.id});if($pr.Count-ne 1){Fail 'P0-REMINDER-SCHEMA-001'}else{$pf=@($pr[0].field_groups|ForEach-Object{$_.fields}|ForEach-Object{$_});Exact @($r.exact_fields_in_order) $pf 'P0-REMINDER-SCHEMA-001'};Has $r.text_rule @('no') 'P0-REMINDER-PRIVACY-001'}
$ledger=@($records|Where-Object{$_.id -eq 'operation_ledger'})[0];if($ledger.bounds.field_mask_codes-ne 5-or$ledger.bounds.ownership_codes-ne 4-or$ledger.bounds.attempt_count_max-ne 3){Fail 'P0-REMINDER-SCHEMA-001'}
if(@($records.exact_fields_in_order|ForEach-Object{$_}|Where-Object{$_-match'(?i)reminder_time|reminder_time_digest|reminder_time_override'}).Count-ne 0){Fail 'P0-REMINDER-DIRECT-EDIT-001'}

$c=$m.catalogs
Ordered @($c.adapter_code) @('microsoft_todo','outlook_calendar') 'P0-REMINDER-CATALOGS-001';Ordered @($c.artifact_type_code) @('todo_task','calendar_reminder_event') 'P0-REMINDER-CATALOGS-001'
Ordered @($c.operation_kind_code) @('todo_create','todo_update_owned_fields','todo_complete','calendar_reminder_create','calendar_reminder_update_owned_fields','manual_todo_create','manual_calendar_create','recreate_after_user_confirmation') 'P0-REMINDER-CATALOGS-001'
Ordered @($c.operation_state_code) @('pending','attempt_started','known_no_send_retryable','ambiguous','reconciling','user_assisted','succeeded','definitive_failed','abandoned') 'P0-REMINDER-CATALOGS-001'
Ordered @($c.reconciliation_code) @('not_required','pending','complete_zero','complete_one','complete_many','incomplete','marker_missing','marker_unsupported','marker_removed','version_changed','account_mismatch','authority_changed','rollback_suspected') 'P0-REMINDER-CATALOGS-001'
Ordered @($c.field_mask_code) @('title','body','due','reminder_time','completion') 'P0-REMINDER-CATALOGS-001';Ordered @($c.ownership_code) @('service_projection','user_owned','user_authoritative','not_applicable') 'P0-REMINDER-CATALOGS-001'
if(@($c.operation_kind_code|Where-Object{$_-match'^(send|delete|bulk|invite|respond|attendee|generic)$'}).Count-ne 0){Fail 'P0-REMINDER-CATALOGS-001'}

Has ($m.todo_boundary|ConvertTo-Json -Depth 10 -Compress) @('Tasks.ReadWrite from disabled PERM-TODO-WRITE-001','explicit user enablement','Tasks.Read remains validation-only','ordinary bounded complete list and task enumeration','delta is not a launch dependency','explicit user-selected eligible owned list','no guessed Tasks or Flagged Email target','application permissions','shared list authority','automatic delete','title body or due identity matching','Calendar substitution after denial') 'P0-REMINDER-TODO-BASELINE-001'
$perm=Json $PermissionPath 'P0-REMINDER-CROSS-CONTRACT-001';$tw=@($perm.permission_rows|Where-Object{$_.id -eq 'PERM-TODO-WRITE-001'});$tr=@($perm.permission_rows|Where-Object{$_.id -eq 'PERM-TODO-DIAG-001'});if($tw.Count-ne 1-or$tw[0].permission-ne'Tasks.ReadWrite'-or$tw[0].state-ne'disabled'-or$tw[0].advertised-ne$false-or$tr.Count-ne 1-or$tr[0].permission-ne'Tasks.Read'-or$tr[0].kind-ne'graph_delegated_validation_only'){Fail 'P0-REMINDER-TODO-BASELINE-001'}

$op=$m.operation_protocol;Ordered @($op.intent_hmac_input_order) @('operation-key-v1','account_ref','adapter_code','collection_ref','loop_id','source_ref_id_or_none','source_generation','operation_kind_code','canonical_field_mask_codes','expected_loop_version','expected_remote_version_hmac_or_none','transient_title_digest_hmac_or_none','transient_body_digest_hmac_or_none','transient_due_digest_hmac_or_none','transient_reminder_time_digest_hmac_or_none','policy_version','authorization_generation','recreate_generation') 'P0-REMINDER-OPERATION-PROTOCOL-001'
Ordered @($op.durability_order) @('validate current account source loop ownership policy and authorization generations','compute operation_key_hmac without retaining readable intent','commit pending ledger entry under ADR-005 before request','revalidate account authority versions and rollback state','mark attempt_started atomically','make at most one adapter request','classify response before any retry or cursor advancement') 'P0-REMINDER-OPERATION-PROTOCOL-001'
Has ($op|ConvertTo-Json -Compress) @('zero new request','operation_key_collision','at most 3','prevent dependent cursor advancement','reconstructed from current evidence and policy','manual draft is never persisted and cannot auto-resume','remote failure never rolls it back') 'P0-REMINDER-OPERATION-PROTOCOL-001'

$rm=$m.remote_marker_protocol;Has ($rm|ConvertTo-Json -Depth 10 -Compress) @('unproven until','base32url of SHA-256','canonical operation_id bytes','remote_correlation_hmac only','no raw marker is persisted','never a title body due URL or link label','bounded complete enumeration','incomplete paging is never zero','complete_zero','complete_one','complete_many','user-assisted duplicate selection','no automatic retry','explicit user confirmation with duplicate warning','new operation identity') 'P0-REMINDER-AMBIGUOUS-WRITE-001'

$own=@($m.ownership_matrix);if($own.Count-ne 9){Fail 'P0-REMINDER-OWNERSHIP-001'}
foreach($origin in @('email_evidence','calendar_invitation')){foreach($field in @('title','body','due')){$x=@($own|Where-Object{$_.origin-eq$origin-and$_.field-eq$field});if($x.Count-ne 1-or$x[0].direct_edit-notlike'user_owned*'){Fail 'P0-REMINDER-OWNERSHIP-001'}}}
foreach($field in @('title','body','due')){$x=@($own|Where-Object{$_.origin-eq'user_authored_microsoft_artifact'-and$_.field-eq$field});if($x.Count-ne 1-or$x[0].initial-ne'user_authoritative'-or$x[0].service_update-ne'prohibited'){Fail 'P0-REMINDER-OWNERSHIP-001'}}
Has ($m.direct_edit_and_conflict|ConvertTo-Json -Compress) @('re-fetch current artifact','compare exact owned field digests and version','no PATCH until adapter-specific conditional-write behavior is proven','patch only the exact service-owned field mask','preserve every user-owned sibling field') 'P0-REMINDER-CONFLICT-001'
Has ($m.direct_edit_and_conflict|ConvertTo-Json -Compress) @('completed_needs_evidence and never closes','explicit confirmation flow','neither fabricates closure','automatic_delete":"prohibited') 'P0-REMINDER-DIRECT-EDIT-001'
Has ($m.reminder_time_boundary|ConvertTo-Json -Compress) @('transiently recompute','encrypted user reminder_lead_rule','no reminder-time value ownership digest or override field is approved','invents none','unmanaged','zero automatic overwrite','only inside operation_key_hmac') 'P0-REMINDER-DIRECT-EDIT-001'

Has ($m.manual_artifact_protocol|ConvertTo-Json -Compress) @('explicit user action','complete nonpersistent draft','proven single success or explicit selection','atomically create exactly one user_authored_artifact_ref loop source relation and reminder link','leaves no durable manual loop or readable draft','never recreate automatically','exactly one authoritative artifact source is proven','same verified account adapter collection and artifact locator tuple') 'P0-REMINDER-MANUAL-SOURCE-001'
Has ($m.calendar_boundary|ConvertTo-Json -Compress) @('unresolved_least_delegated_calendar_scope:G-CAL','no guessed scope or request','self-only event with zero attendees no online meeting no response request','no invitation update cancellation mail','never responds changes attendees updates deletes or cancels','zero multiple or incomplete results','no completion operation','does not support complete-MVP calendar or invitation claims') 'P0-REMINDER-CALENDAR-SAFETY-001'
Ordered @($m.review_link_boundary.prohibited) @('bearer token','pairing token','session secret','Graph or Office ID','account identifier','mailbox content','host port or URL authority','raw evidence link') 'P0-REMINDER-REVIEW-LINK-001';Has ($m.review_link_boundary|ConvertTo-Json -Compress) @('one random non-secret opaque loop handle only','authority":"none','ADR-010 authenticated per-user account-bound session','unavailable pending ADR-010 and G-ADDIN') 'P0-REMINDER-REVIEW-LINK-001'
Ordered @($m.privacy_boundary.approved_record_types) @('reminder_link','operation_ledger','user_authored_artifact_ref') 'P0-REMINDER-PRIVACY-001';Has ($m.privacy_boundary|ConvertTo-Json -Compress) @('human-readable title body due phrase reminder text or draft','raw Microsoft Graph Office account list artifact event task or URL identifier','raw remote marker request response error or authorization value','free-text conflict correction explanation or note','generic JSON map extension bag open enum unbounded string bytes array or blob','prompt model request response output rationale embedding transcript or vector','fixed non-content adapter operation reconciliation failure and count codes only','disabled') 'P0-REMINDER-PRIVACY-001'

$sd=$m.separate_decisions;if($sd.mode_semantics_eligibility_evaluation_flags_and_rollback-ne'ADR-011'-or$sd.review_link_activation_pairing_session_and_client_matrix-ne'ADR-010'-or$sd.self_email_send_recipient_and_operation_protocol-ne'ADR-013'-or$sd.storage_encryption_atomicity_and_rollback-ne'ADR-005'-or$sd.persistent_field_allowlist_and_retention-ne'ADR-PRIV-001'){Fail 'P0-REMINDER-DEFERRED-001'}
$gov=Json $GovernancePath 'P0-REMINDER-CROSS-CONTRACT-001';$a9=@($gov.adrs|Where-Object{$_.id -eq 'ADR-009'});if($a9.Count-ne 1-or$a9[0].status-ne'accepted'-or@($gov.gates|Where-Object{$_.id-in$m.blocking_gates-and$_.status-ne'unrun'}).Count-ne 0){Fail 'P0-REMINDER-CROSS-CONTRACT-001'}
$persist=Json $PersistencePath 'P0-REMINDER-CROSS-CONTRACT-001';if($persist.logical_schema_boundary.logical_runtime_schema_approved-ne$false-or$persist.separate_decisions.reminder_ownership_and_operation_catalogs-ne'ADR-009'){Fail 'P0-REMINDER-CROSS-CONTRACT-001'}
$policy=Json $PolicyPath 'P0-REMINDER-CROSS-CONTRACT-001';if($policy.reminder_boundary.local_policy_only-ne$true){Fail 'P0-REMINDER-CROSS-CONTRACT-001'};Empty @($policy.reminder_boundary.graph_office_permissions_calls_operations) 'P0-REMINDER-CROSS-CONTRACT-001'
$evidence=Json $EvidencePath 'P0-REMINDER-CROSS-CONTRACT-001';Has ($evidence.unavailable_projection|ConvertTo-Json -Compress) @('never closes resolves dismisses or proves failure') 'P0-REMINDER-CROSS-CONTRACT-001'
$sync=Json $SyncPath 'P0-REMINDER-CROSS-CONTRACT-001';Empty @($sync.claims.graph_calls) 'P0-REMINDER-CROSS-CONTRACT-001';Empty @($sync.claims.network_contacts) 'P0-REMINDER-CROSS-CONTRACT-001'
$support=Json $SupportPath 'P0-REMINDER-CROSS-CONTRACT-001';foreach($n in @('supported_rows','enabled_capabilities','advertised_capabilities','gates_passed','acceptance_criteria_completed')){Empty @($support.claim_state.$n) 'P0-REMINDER-CROSS-CONTRACT-001'}
$build=Json $BuildPath 'P0-REMINDER-CROSS-CONTRACT-001';if($build.runtime_boundary.durable_state-ne$false-or$build.runtime_boundary.graph_transport-ne$false){Fail 'P0-REMINDER-CROSS-CONTRACT-001'};Empty @($build.runtime_boundary.network_origins) 'P0-REMINDER-CROSS-CONTRACT-001'

$rt=$m.runtime_boundary;if($rt.adapter_runtime-ne$false-or$rt.logical_records_accepted-ne$false){Fail 'P0-REMINDER-CLAIMS-001'};foreach($n in @('persistent_records_created','network_calls','graph_office_calls','mutations','permissions_requested','dependencies_activated','acceptance_criteria_completed','scenarios_completed','gates_passed')){Empty @($rt.$n) 'P0-REMINDER-CLAIMS-001'};foreach($n in @('capabilities_enabled','capabilities_advertised','support_rows_advertised','todo_collections_supported','calendar_behaviors_supported','remote_markers_proven','conditional_writes_proven')){Empty @($m.claims.$n) 'P0-REMINDER-CLAIMS-001'}

$adr=Text $AdrPath 'P0-REMINDER-CROSS-CONTRACT-001';$threat=Text $ThreatPath 'P0-REMINDER-CROSS-CONTRACT-001';$spec=Text $ProductSpecPath 'P0-REMINDER-INVENTORY-001';$plan=Text $ImplementationPlanPath 'P0-REMINDER-INVENTORY-001';$trace=Text $TraceabilityPath 'P0-REMINDER-INVENTORY-001'
if((NHash $adr)-ne'e1743869d348753cfd3874454a604e54f721e3cdf7d768770d5d239ca8c8ba73'){Fail 'P0-REMINDER-CROSS-CONTRACT-001'};if((NHash $spec)-ne'c0a7718d78bde3804142e5b79a937a8d66a372bfe35406e2c8b2ce96d4c7ed54'){Fail 'P0-REMINDER-INVENTORY-001'};if((NHash $plan)-ne'eda5228cfa8e2228027d419eb4ec1ac5d1ce003777247cc6b5b80be467674bee'){Fail 'P0-REMINDER-INVENTORY-001'};if((NHash $trace)-ne'acc01674336de4d3efca3ff3c68289694054eb0f9f64ca6bdbeb5a3e45f2127b'){Fail 'P0-REMINDER-INVENTORY-001'}
Has $adr @('Status:** Accepted','P0-WI-12','OWN-03, OWN-04, OWN-05, OWN-07','pending encrypted operation-ledger record','The local operation key is not remote idempotency','never automatically deletes','requests no guessed scope','one random, non-secret opaque loop handle','accepts only this disabled decision contract') 'P0-REMINDER-CROSS-CONTRACT-001'
Has $threat @('Reminder adapter boundary','Durable operation first','Readable content or identifiers enter state','Remote direct edit is overwritten','Reminder controls loop lifecycle','Calendar action emails or affects another person','Review link becomes a credential','Manual draft survives a crash','Rollback, account, authorization, or version drift') 'P0-REMINDER-CROSS-CONTRACT-001'
$ids=[regex]::Matches($trace,'(?m)^\| (P0-REMINDER-[A-Z-]+-001) \|')|ForEach-Object{$_.Groups[1].Value};Exact @($ids) $checks 'P0-REMINDER-INVENTORY-001';foreach($id in $checks){if(([regex]::Matches($trace,'\b'+[regex]::Escape($id)+'\b')).Count-ne 1){Fail 'P0-REMINDER-INVENTORY-001'}}
$fresh=[regex]::Match($trace,'(?m)^\| P0-REMINDER-FRESH-CHECKER-001 \|.*$').Value;Has $fresh @('Fresh-context privacy, protocol, scope, and adversarial judges','no prompt, transcript, or model output stored','Pending closure') 'P0-REMINDER-FRESH-CHECKER-001'
if($script:fail.Count-gt 0){[Console]::Error.WriteLine(('FAIL: reminder adapter boundary: '+(($script:fail|Sort-Object)-join', ')));exit 1};if(-not$Quiet){Write-Output ('PASS: reminder adapter boundary ({0} checks; runtime, calls, permissions, records, and claims disabled)' -f $checks.Count)}
