[CmdletBinding()]param([string]$CheckerPath='tools/check-self-email-boundary.ps1')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repoRoot=(& git rev-parse --show-toplevel 2>$null).Trim();if($LASTEXITCODE-ne 0-or[string]::IsNullOrWhiteSpace($repoRoot)){throw'Run inside the repository.'}
function Resolve-Repo([string]$p){if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path $repoRoot $p))}}
$checker=Resolve-Repo $CheckerPath
$inputs=@('contracts/selfemail/self-email-boundary.json','docs/adr/ADR-013-self-email.md','docs/threat-model/self-email.md','docs/prd-traceability.md','docs/product-spec.md','docs/implementation-plan.md','contracts/governance/capabilities.json','docs/adr/ADR-003-incremental-authorization.md','docs/adr/ADR-004-synchronization.md','docs/adr/ADR-005-persistence-and-cryptography.md','docs/adr/ADR-009-reminder-adapters.md','docs/adr/ADR-PRIV-001-derived-metadata-and-source-boundary.md','contracts/support/support-matrix.json','contracts/build-skeleton/skeleton.json','contracts/domain/policy-state-boundary.json','contracts/reminder/adapter-boundary.json','contracts/addin/bridge-boundary.json','contracts/automation/evaluation-boundary.json','contracts/distribution/registration-boundary.json')
$script:count=0;$script:fail=[Collections.Generic.List[string]]::new()
function New-Root{$root=Join-Path ([IO.Path]::GetTempPath()) ('openloops-selfemail-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null;foreach($rel in $inputs){$target=Join-Path $root $rel;[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($target))|Out-Null;Copy-Item -LiteralPath (Join-Path $repoRoot $rel) -Destination $target};$root}
function Check([string]$root){$a=@('-NoProfile','-File',$checker,'-ManifestPath',(Join-Path $root 'contracts/selfemail/self-email-boundary.json'),'-AdrPath',(Join-Path $root 'docs/adr/ADR-013-self-email.md'),'-ThreatPath',(Join-Path $root 'docs/threat-model/self-email.md'),'-TraceabilityPath',(Join-Path $root 'docs/prd-traceability.md'),'-ProductSpecPath',(Join-Path $root 'docs/product-spec.md'),'-ImplementationPlanPath',(Join-Path $root 'docs/implementation-plan.md'),'-GovernancePath',(Join-Path $root 'contracts/governance/capabilities.json'),'-Adr003Path',(Join-Path $root 'docs/adr/ADR-003-incremental-authorization.md'),'-Adr004Path',(Join-Path $root 'docs/adr/ADR-004-synchronization.md'),'-Adr005Path',(Join-Path $root 'docs/adr/ADR-005-persistence-and-cryptography.md'),'-Adr009Path',(Join-Path $root 'docs/adr/ADR-009-reminder-adapters.md'),'-AdrPrivPath',(Join-Path $root 'docs/adr/ADR-PRIV-001-derived-metadata-and-source-boundary.md'),'-SupportPath',(Join-Path $root 'contracts/support/support-matrix.json'),'-BuildPath',(Join-Path $root 'contracts/build-skeleton/skeleton.json'),'-PolicyPath',(Join-Path $root 'contracts/domain/policy-state-boundary.json'),'-ReminderPath',(Join-Path $root 'contracts/reminder/adapter-boundary.json'),'-AddinPath',(Join-Path $root 'contracts/addin/bridge-boundary.json'),'-AutomationPath',(Join-Path $root 'contracts/automation/evaluation-boundary.json'),'-DistributionPath',(Join-Path $root 'contracts/distribution/registration-boundary.json'),'-Quiet');$o=@(& pwsh @a 2>&1|ForEach-Object{[string]$_});[pscustomobject]@{Code=$LASTEXITCODE;Output=($o-join"`n")}}
function JsonCase([string]$name,[string]$id,[string]$rel,[scriptblock]$mutate){$script:count++;$root=New-Root;try{$path=Join-Path $root $rel;$v=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json -Depth 100;&$mutate $v;$v|ConvertTo-Json -Depth 100|Set-Content -LiteralPath $path -Encoding utf8NoBOM;$r=Check $root;if($r.Code-eq 0-or$r.Output-notmatch[regex]::Escape($id)){$script:fail.Add("$name (expected $id; exit $($r.Code))")}}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}}
function TextCase([string]$name,[string]$id,[string]$rel,[scriptblock]$mutate){$script:count++;$root=New-Root;try{$path=Join-Path $root $rel;$changed=&$mutate (Get-Content -Raw -LiteralPath $path);Set-Content -LiteralPath $path -Value $changed -Encoding utf8NoBOM;$r=Check $root;if($r.Code-eq 0-or$r.Output-notmatch[regex]::Escape($id)){$script:fail.Add("$name (expected $id; exit $($r.Code))")}}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}}
$base=& pwsh -NoProfile -File $checker 2>&1;if($LASTEXITCODE-ne 0){throw('Baseline self-email checker failed: '+(@($base)-join"`n"))}

# Recipient policy
JsonCase 'second recipient added' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.legal_recipient='the authenticated account and a configured backup address both receive the summary'}
JsonCase 'cc added to prohibited list removed' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.prohibited=@($c.recipient_policy.prohibited|Where-Object{$_ -ne 'Cc'})}
JsonCase 'bcc prohibition removed' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.prohibited=@($c.recipient_policy.prohibited|Where-Object{$_ -ne 'Bcc'})}
JsonCase 'recipient sourced from user input permitted' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.prohibited=@($c.recipient_policy.prohibited|Where-Object{$_ -ne 'a recipient sourced from user input'})}
JsonCase 'reply-to redirection permitted' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.prohibited=@($c.recipient_policy.prohibited|Where-Object{$_ -ne 'reply-to redirection'})}
JsonCase 'distribution list permitted' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.prohibited=@($c.recipient_policy.prohibited|Where-Object{$_ -ne 'distribution lists'})}
JsonCase 'canonical recipient source guessed ahead of gate' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recipient_policy.canonical_source='graph_me_mail_field is the selected canonical source'}
JsonCase 'canonical recipient candidate catalog narrowed' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.canonical_recipient_source_candidate_code=@($c.catalogs.canonical_recipient_source_candidate_code|Where-Object{$_ -ne 'primary_smtp_proxy_address'})}
JsonCase 'recipient policy catalog narrowed' 'P0-SELFMAIL-RECIPIENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.recipient_policy_code=@($c.catalogs.recipient_policy_code|Where-Object{$_ -ne 'no_distribution_list'})}

# Consent policy
JsonCase 'Mail.Send bundled into initial consent' 'P0-SELFMAIL-CONSENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.consent_policy.consent='Mail.Send is requested together with the initial sign-in consent grant'}
JsonCase 'consent loss does not stop sends' 'P0-SELFMAIL-CONSENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.consent_policy.loss_behavior='a send already scheduled continues even after consent is revoked'}
JsonCase 'consent policy catalog narrowed' 'P0-SELFMAIL-CONSENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.consent_policy_code=@($c.catalogs.consent_policy_code|Where-Object{$_ -ne 'consent_loss_stops_sends_before_request'})}
JsonCase 'enablement no longer separate' 'P0-SELFMAIL-CONSENT-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.consent_policy.enablement='enabled automatically once the account signs in'}

# Marker policy
JsonCase 'marker carries summary content' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.marker_policy.content_boundary='the marker embeds the first line of summary content for convenience'}
JsonCase 'marker carries a secret' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.marker_policy.content_boundary='the marker embeds the raw operation-ledger encryption key'}
JsonCase 'marker by subject text substitute' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.marker_policy.verification='detection matches the exact subject line text used by generated summaries'}
JsonCase 'marker excludes user-authored mail' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.marker_policy.exclusion_scope='any message whose subject resembles a summary is excluded from detection, including a user-authored message'}
JsonCase 'marker mechanism catalog narrowed' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.marker_mechanism_candidate_code=@($c.catalogs.marker_mechanism_candidate_code|Where-Object{$_ -ne 'graph_multi_value_extended_property'})}
JsonCase 'marker mechanism preselected' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.marker_policy.mechanism_candidates='custom_internet_message_header is the selected mechanism'}
JsonCase 'marker policy catalog narrowed' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.marker_policy_code=@($c.catalogs.marker_policy_code|Where-Object{$_ -ne 'never_marker_by_subject_text'})}
JsonCase 'marker does not survive round trip' 'P0-SELFMAIL-MARKER-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.marker_policy.round_trip='the marker may be dropped by transport and is not required on the saved copy'}

# Recursion suppression
JsonCase 'recursion suppression removed for summary-of-summary' 'P0-SELFMAIL-RECURSION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recursion_suppression.prevented_paths=@($c.recursion_suppression.prevented_paths|Where-Object{$_ -ne 'summary-of-summary inclusion'})}
JsonCase 'recursion suppression removed for loop creation' 'P0-SELFMAIL-RECURSION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recursion_suppression.prevented_paths=@($c.recursion_suppression.prevented_paths|Where-Object{$_ -ne 'loop creation'})}
JsonCase 'suppression failure treated as best effort' 'P0-SELFMAIL-RECURSION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recursion_suppression.failure_mode='if the marker cannot be verified the message is summarized anyway on a best-effort basis'}
JsonCase 'recursion suppression catalog narrowed' 'P0-SELFMAIL-RECURSION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.recursion_suppression_code=@($c.catalogs.recursion_suppression_code|Where-Object{$_ -ne 'suppression_failure_fails_closed_to_no_send'})}
JsonCase 'marker check order removed' 'P0-SELFMAIL-RECURSION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.recursion_suppression.check_order='loop-creation logic runs before any marker check'}

# Operation protocol
JsonCase 'send without durable pending operation' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.send_operation_protocol.durability='the send request is issued immediately and the ledger entry is written afterward if the send succeeds'}
JsonCase 'blind retry after ambiguous send' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.send_operation_protocol.ambiguous_reconciliation='an ambiguous outcome is retried immediately without reconciliation'}
JsonCase 'more than one request per attempt' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.send_operation_protocol.request_cardinality='up to three requests may be issued for a single recorded attempt to improve delivery odds'}
JsonCase 'definitive failure silently swallowed' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.send_operation_protocol.definitive_failure='a definitively failed send is logged internally without surfacing to the user'}
JsonCase 'operation protocol catalog narrowed' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.operation_protocol_code=@($c.catalogs.operation_protocol_code|Where-Object{$_ -ne 'lost_response_never_blindly_retried'})}
JsonCase 'failure boundary trigger removed: secure-store loss' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.failure_boundary.triggers=@($c.failure_boundary.triggers|Where-Object{$_ -ne 'secure-store loss'})}
JsonCase 'failure boundary trigger removed: rollback suspicion' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.failure_boundary.triggers=@($c.failure_boundary.triggers|Where-Object{$_ -ne 'rollback suspicion'})}
JsonCase 'failure boundary trigger removed: account mismatch' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.failure_boundary.triggers=@($c.failure_boundary.triggers|Where-Object{$_ -ne 'account mismatch'})}
JsonCase 'failure boundary allows partial success' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.failure_boundary.result='a partial success is accepted if the ledger entry was written even without a confirmed remote result'}
JsonCase 'failure boundary catalog narrowed' 'P0-SELFMAIL-OPERATION-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.failure_boundary_code=@($c.catalogs.failure_boundary_code|Where-Object{$_ -ne 'marker_verification_failure_causes_zero_requests'})}

# Schedule policy
JsonCase 'catch-up burst of missed schedules' 'P0-SELFMAIL-SCHEDULE-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.schedule_policy.catch_up_prohibition='every missed occurrence is resent in a burst once connectivity returns'}
JsonCase 'scheduled send runs while disconnected' 'P0-SELFMAIL-SCHEDULE-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.schedule_policy.eligibility='a scheduled send proceeds even if the account is not currently authenticated'}
JsonCase 'schedule policy catalog narrowed' 'P0-SELFMAIL-SCHEDULE-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.schedule_policy_code=@($c.catalogs.schedule_policy_code|Where-Object{$_ -ne 'no_catch_up_burst'})}
JsonCase 'missed schedule handling removed' 'P0-SELFMAIL-SCHEDULE-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.schedule_policy.missed_schedule_handling='a missed schedule is simply skipped with no coalesced next run'}

# Privacy / generation policy
JsonCase 'stored summary copy introduced' 'P0-SELFMAIL-PRIVACY-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.generation_policy.no_stored_copy='the rendered summary is cached locally to speed up the next scheduled send'}
JsonCase 'draft or template output stored' 'P0-SELFMAIL-PRIVACY-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.generation_policy.no_stored_copy='a draft is saved to the account Drafts folder before send'}
JsonCase 'generation content rules diverge from privacy boundary' 'P0-SELFMAIL-PRIVACY-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.generation_policy.content_rules='self-email content may include raw evidence text not otherwise persisted'}
JsonCase 'generation policy catalog narrowed' 'P0-SELFMAIL-PRIVACY-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.catalogs.generation_policy_code=@($c.catalogs.generation_policy_code|Where-Object{$_ -ne 'no_stored_summary_copy'})}
JsonCase 'unresolved mechanics catalog narrowed' 'P0-SELFMAIL-PRIVACY-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.'unresolved_pending_G-SELFMAIL'=@($c.'unresolved_pending_G-SELFMAIL'|Where-Object{$_ -ne 'marker mechanism'})}

# Claims
JsonCase 'gate-passed claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.runtime_boundary.gates_passed=@('G-SELFMAIL')}
JsonCase 'mail send requested claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.runtime_boundary.mail_send_requested=$true}
JsonCase 'self email sent claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.runtime_boundary.self_email_sent=$true}
JsonCase 'marker mechanism selected claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.runtime_boundary.marker_mechanism_selected=$true}
JsonCase 'scheduled send active claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.runtime_boundary.scheduled_send_active=$true}
JsonCase 'capability-enabled claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.claims.capabilities_enabled=@('self_email_summary')}
JsonCase 'recipient source advertised claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.claims.recipient_sources_advertised=@('graph_me_mail_field')}
JsonCase 'marker mechanism advertised claim' 'P0-SELFMAIL-CLAIMS-001' 'contracts/selfemail/self-email-boundary.json' {param($c)$c.claims.marker_mechanisms_advertised=@('custom_internet_message_header')}

# Cross-contract
JsonCase 'ADR-013 prematurely reverted to planned' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.adrs|Where-Object{$_.id -eq 'ADR-013'}).status='planned'}
JsonCase 'self-email capability enabled in governance' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.capabilities|Where-Object{$_.id -eq 'self_email_summary'}).state='enabled'}
JsonCase 'self-email capability advertised in governance' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.capabilities|Where-Object{$_.id -eq 'self_email_summary'}).advertised=$true}
JsonCase 'gate marked passed in governance' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.gates|Where-Object{$_.id -eq 'G-SELFMAIL'}).status='passed'}
JsonCase 'OWN-10 reopened in governance' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.owner_decisions|Where-Object{$_.id -eq 'OWN-10'}).status='reopened'}
JsonCase 'support matrix claims a supported row' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/support/support-matrix.json' {param($c)$c.claim_state.supported_rows=@('self_email_summary')}
JsonCase 'build skeleton claims graph transport runtime' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/build-skeleton/skeleton.json' {param($c)$c.runtime_boundary.graph_transport=$true}
JsonCase 'build skeleton claims a gate passed' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'contracts/build-skeleton/skeleton.json' {param($c)$c.gates_passed=@('G-SELFMAIL')}
JsonCase 'reminder manifest claims OL-SUM ownership' 'P0-SELFMAIL-INVENTORY-001' 'contracts/reminder/adapter-boundary.json' {param($c)$c.owned_requirements=@($c.owned_requirements)+@('OL-SUM-004')}

TextCase 'ADR-003 Mail.Send wording removed' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'docs/adr/ADR-003-incremental-authorization.md' {param($t)$t-replace'Self-email adds `Mail.Send` only through separate explicit','Self-email adds `Mail.Send` through any convenient'}
TextCase 'ADR-004 sent-copy observation wording removed' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'docs/adr/ADR-004-synchronization.md' {param($t)$t-replace'A saved sent copy may be analyzed once, but drafts\s+and compose activity never activate loops','Every saved sent copy and every draft may activate a loop'}
TextCase 'ADR-005 operation-ledger wording removed' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'docs/adr/ADR-005-persistence-and-cryptography.md' {param($t)$t-replace'pending operation identity precedes an external request;\s+ambiguous writes reconcile before retry','a request may be issued before any pending operation identity exists'}
TextCase 'ADR-009 durable-before-request wording removed' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'docs/adr/ADR-009-reminder-adapters.md' {param($t)$t-replace'Every remote mutation begins with a pending encrypted operation-ledger record','A remote mutation may begin with an immediate request and no operation-ledger record'}
TextCase 'ADR-PRIV-001 generated-summary prohibition removed' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'docs/adr/ADR-PRIV-001-derived-metadata-and-source-boundary.md' {param($t)$t-replace'generated\s+summaries or explanations','narrated summaries or explanations except a retained self-email copy'}

TextCase 'spec contradiction appended' 'P0-SELFMAIL-INVENTORY-001' 'docs/product-spec.md' {param($t)$t+"`nContrary rule: self-email may address any recipient the user types.`n"}
TextCase 'plan contradiction appended' 'P0-SELFMAIL-INVENTORY-001' 'docs/implementation-plan.md' {param($t)$t+"`nP0-WI-16 sends the first self-email summary.`n"}
TextCase 'ADR contradiction appended' 'P0-SELFMAIL-CROSS-CONTRACT-001' 'docs/adr/ADR-013-self-email.md' {param($t)$t+"`nContrary decision: a second recipient may be added once the feature is popular.`n"}
TextCase 'trace contradiction appended' 'P0-SELFMAIL-INVENTORY-001' 'docs/prd-traceability.md' {param($t)$t+"`nP0-WI-16 passed G-SELFMAIL and G-PRIV and sends the daily self-email.`n"}
TextCase 'fresh checker preapproved' 'P0-SELFMAIL-FRESH-CHECKER-001' 'docs/prd-traceability.md' {param($t)$t-replace'\| P0-SELFMAIL-FRESH-CHECKER-001 \|([^\n]*)Passed at P0-WI-16 closure','| P0-SELFMAIL-FRESH-CHECKER-001 |$1Passed without independent review'}
TextCase 'fresh checker closure regressed to pending' 'P0-SELFMAIL-FRESH-CHECKER-001' 'docs/prd-traceability.md' {param($t)$t-replace'\| P0-SELFMAIL-FRESH-CHECKER-001 \|([^\n]*)Passed at P0-WI-16 closure','| P0-SELFMAIL-FRESH-CHECKER-001 |$1Pending closure'}

if($script:fail.Count-gt 0){[Console]::Error.WriteLine(('FAIL: self-email synthetic mutations: '+($script:fail-join'; ')));exit 1};Write-Output ('PASS: self-email synthetic mutations ({0} rejection cases; OS temp only)' -f $script:count)
