[CmdletBinding()]param([string]$CheckerPath='tools/check-distribution-registration-boundary.ps1')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repoRoot=(& git rev-parse --show-toplevel 2>$null).Trim();if($LASTEXITCODE-ne 0-or[string]::IsNullOrWhiteSpace($repoRoot)){throw'Run inside the repository.'}
function Resolve-Repo([string]$p){if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path $repoRoot $p))}}
$checker=Resolve-Repo $CheckerPath
$inputs=@('contracts/distribution/registration-boundary.json','docs/adr/ADR-012-distribution-and-registration.md','docs/threat-model/distribution-and-update.md','docs/prd-traceability.md','docs/product-spec.md','docs/implementation-plan.md','contracts/governance/capabilities.json','docs/adr/ADR-001-runtime-and-self-hosting-boundary.md','docs/adr/ADR-005-persistence-and-cryptography.md','docs/adr/ADR-010-add-in-bridge.md','docs/adr/ADR-PRIV-001-derived-metadata-and-source-boundary.md','contracts/support/support-matrix.json','contracts/build-skeleton/skeleton.json','contracts/domain/policy-state-boundary.json','contracts/reminder/adapter-boundary.json','contracts/addin/bridge-boundary.json','contracts/automation/evaluation-boundary.json','Cargo.toml','package.json','AGENTS.md')
$script:count=0;$script:fail=[Collections.Generic.List[string]]::new()
function New-Root{$root=Join-Path ([IO.Path]::GetTempPath()) ('openloops-distribution-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null;foreach($rel in $inputs){$target=Join-Path $root $rel;[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($target))|Out-Null;Copy-Item -LiteralPath (Join-Path $repoRoot $rel) -Destination $target};$root}
function Check([string]$root){$a=@('-NoProfile','-File',$checker,'-ManifestPath',(Join-Path $root 'contracts/distribution/registration-boundary.json'),'-AdrPath',(Join-Path $root 'docs/adr/ADR-012-distribution-and-registration.md'),'-ThreatPath',(Join-Path $root 'docs/threat-model/distribution-and-update.md'),'-TraceabilityPath',(Join-Path $root 'docs/prd-traceability.md'),'-ProductSpecPath',(Join-Path $root 'docs/product-spec.md'),'-ImplementationPlanPath',(Join-Path $root 'docs/implementation-plan.md'),'-GovernancePath',(Join-Path $root 'contracts/governance/capabilities.json'),'-Adr001Path',(Join-Path $root 'docs/adr/ADR-001-runtime-and-self-hosting-boundary.md'),'-Adr005Path',(Join-Path $root 'docs/adr/ADR-005-persistence-and-cryptography.md'),'-Adr010Path',(Join-Path $root 'docs/adr/ADR-010-add-in-bridge.md'),'-AdrPrivPath',(Join-Path $root 'docs/adr/ADR-PRIV-001-derived-metadata-and-source-boundary.md'),'-SupportPath',(Join-Path $root 'contracts/support/support-matrix.json'),'-BuildPath',(Join-Path $root 'contracts/build-skeleton/skeleton.json'),'-PolicyPath',(Join-Path $root 'contracts/domain/policy-state-boundary.json'),'-ReminderPath',(Join-Path $root 'contracts/reminder/adapter-boundary.json'),'-AddinPath',(Join-Path $root 'contracts/addin/bridge-boundary.json'),'-AutomationPath',(Join-Path $root 'contracts/automation/evaluation-boundary.json'),'-CargoPath',(Join-Path $root 'Cargo.toml'),'-PackageJsonPath',(Join-Path $root 'package.json'),'-AgentsPath',(Join-Path $root 'AGENTS.md'),'-Quiet');$o=@(& pwsh @a 2>&1|ForEach-Object{[string]$_});[pscustomobject]@{Code=$LASTEXITCODE;Output=($o-join"`n")}}
function JsonCase([string]$name,[string]$id,[string]$rel,[scriptblock]$mutate){$script:count++;$root=New-Root;try{$path=Join-Path $root $rel;$v=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json -Depth 100;&$mutate $v;$v|ConvertTo-Json -Depth 100|Set-Content -LiteralPath $path -Encoding utf8NoBOM;$r=Check $root;if($r.Code-eq 0-or$r.Output-notmatch[regex]::Escape($id)){$script:fail.Add("$name (expected $id; exit $($r.Code))")}}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}}
function TextCase([string]$name,[string]$id,[string]$rel,[scriptblock]$mutate){$script:count++;$root=New-Root;try{$path=Join-Path $root $rel;$changed=&$mutate (Get-Content -Raw -LiteralPath $path);Set-Content -LiteralPath $path -Value $changed -Encoding utf8NoBOM;$r=Check $root;if($r.Code-eq 0-or$r.Output-notmatch[regex]::Escape($id)){$script:fail.Add("$name (expected $id; exit $($r.Code))")}}finally{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}}
$base=& pwsh -NoProfile -File $checker 2>&1;if($LASTEXITCODE-ne 0){throw('Baseline distribution checker failed: '+(@($base)-join"`n"))}

JsonCase 'tracked client id inserted in registration configuration' 'P0-DIST-REGISTRATION-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.registration_boundary.byo_public_client.configuration='tracks client_id 11111111-1111-1111-1111-111111111111 and tenant_id 22222222-2222-2222-2222-222222222222 in repository configuration'}
JsonCase 'byo status widened beyond only enabled path' 'P0-DIST-REGISTRATION-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.registration_boundary.byo_public_client.status='one of several enabled Phase 0 paths'}
JsonCase 'pkce limitation no longer preserved' 'P0-DIST-REGISTRATION-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.registration_boundary.pkce_limitation_preserved=$false}

JsonCase 'shared registration status weakened' 'P0-DIST-REGISTRATION-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.registration_boundary.shared_project_registration.status='enabled after publisher review'}
JsonCase 'shared registration enablement prohibited-by narrowed' 'P0-DIST-SHARED-GOVERNANCE-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.registration_boundary.shared_project_registration.enablement_prohibited_by=@($c.registration_boundary.shared_project_registration.enablement_prohibited_by|Where-Object{$_ -ne 'a passing test'})}
JsonCase 'shared registration governance control removed' 'P0-DIST-SHARED-GOVERNANCE-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.registration_boundary.shared_project_registration.required_governance_controls=@($c.registration_boundary.shared_project_registration.required_governance_controls|Where-Object{$_ -notmatch 'owner-recovery'})}
JsonCase 'governance control catalog widened with an unresearched control' 'P0-DIST-SHARED-GOVERNANCE-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.catalogs.shared_registration_governance_control_code=@($c.catalogs.shared_registration_governance_control_code)+@('marketing_campaign_approval')}

JsonCase 'update metadata dependence collapse onto package key' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.metadata_signing='signed using the same key and certificate as the installer package'}
JsonCase 'downgrade permitted' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.version_policy='the client accepts any validly signed version, including one older than the currently installed version'}
JsonCase 'channel binding removed' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.channel_binding='metadata from any channel is accepted if the signature validates'}
JsonCase 'expiry removed' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.expiry='metadata never expires once signed'}
JsonCase 'package hash and size no longer pinned' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.package_identity='package identity is inferred from the filename alone'}
JsonCase 'staging becomes non-atomic' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.staging_and_replacement='the package overwrites the running installation directly as each byte downloads, with no staging or recovery path'}
JsonCase 'provenance requirement removed' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.provenance='provenance is optional and a package with no traceable source revision may still be accepted'}
JsonCase 'elevation permitted by default' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.update_trust_chain.elevation='the installer requests administrator elevation by default for every install and update'}
JsonCase 'update trust field catalog narrowed' 'P0-DIST-UPDATE-TRUST-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.catalogs.update_trust_field_code=@($c.catalogs.update_trust_field_code|Where-Object{$_ -ne 'source_revision'})}

JsonCase 'source map allowlisted' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.prohibited=@($c.artifact_boundary.prohibited|Where-Object{$_ -ne 'source maps'})}
JsonCase 'generated diagnostics allowlisted' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.prohibited=@($c.artifact_boundary.prohibited|Where-Object{$_ -ne 'generated diagnostic artifacts'})}
JsonCase 'artifact allowlist rule weakened' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.allowlist_rule='an artifact outside its class allowlist may still ship if the release is otherwise ready'}
JsonCase 'sbom and provenance no longer required' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.sbom_and_provenance='optional for a fast-tracked release'}
JsonCase 'npm publishability narrative weakened' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.npm_publishability='publishable once the package is reviewed once'}
JsonCase 'cargo publishability narrative weakened' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.cargo_publishability='publish = true once a crate is stable'}
JsonCase 'canary gate silenced on failure' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.artifact_boundary.canary_and_public_repo_gates='run only on request and may be skipped for an urgent release'}
JsonCase 'artifact allowlist class catalog narrowed' 'P0-DIST-ARTIFACTS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.catalogs.artifact_allowlist_class_code=@($c.catalogs.artifact_allowlist_class_code|Where-Object{$_ -ne 'provenance_attestation'})}

TextCase 'npm files list widened' 'P0-DIST-ARTIFACTS-001' 'package.json' {param($t)$t-replace'"files": \[\]','"files": ["dist/index.js"]'}
TextCase 'crate publish enabled' 'P0-DIST-ARTIFACTS-001' 'Cargo.toml' {param($t)$t-replace'publish = false','publish = true'}

JsonCase 'installer requires elevation' 'P0-DIST-INSTALLER-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.installer_boundary.install_mode='machine-wide install requiring administrator elevation'}
JsonCase 'uninstall leaves bridge trust behind' 'P0-DIST-INSTALLER-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.installer_boundary.uninstall_completeness='removes the application binaries only; any bridge certificate or trust already issued remains installed'}
JsonCase 'uninstall claims physical erasure' 'P0-DIST-INSTALLER-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.installer_boundary.residual_risk_disclosure='uninstall guarantees the device can never expose prior local state again'}
JsonCase 'uninstall bulk-deletes microsoft artifacts' 'P0-DIST-INSTALLER-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.installer_boundary.microsoft_artifact_handling='uninstall automatically deletes every Microsoft To Do task and calendar reminder it created'}
JsonCase 'installer boundary property catalog narrowed' 'P0-DIST-INSTALLER-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.catalogs.installer_boundary_property_code=@($c.catalogs.installer_boundary_property_code|Where-Object{$_ -ne 'bridge_trust_removed'})}

JsonCase 'diagnostics allowlist non-empty' 'P0-DIST-DIAGNOSTICS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.diagnostics_rule.allowlist='crash_signature_code_only'}
JsonCase 'diagnostics export requirement weakened to a partial subset' 'P0-DIST-DIAGNOSTICS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.diagnostics_rule.future_export_requirement='G-PRIV alone is sufficient before any future diagnostic export'}

JsonCase 'unresolved mechanics catalog narrowed' 'P0-DIST-PRIVACY-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.'unresolved_pending_G-RELEASE'=@($c.'unresolved_pending_G-RELEASE'|Where-Object{$_ -ne 'certificate provider'})}

JsonCase 'gate-passed claim' 'P0-DIST-CLAIMS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.runtime_boundary.gates_passed=@('G-RELEASE')}
JsonCase 'shared registration enabled claim' 'P0-DIST-CLAIMS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.runtime_boundary.shared_registration_enabled=$true}
JsonCase 'package signed claim' 'P0-DIST-CLAIMS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.runtime_boundary.package_signed=$true}
JsonCase 'security audit completed claim' 'P0-DIST-CLAIMS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.runtime_boundary.security_audit_completed=$true}
JsonCase 'capability-enabled claim' 'P0-DIST-CLAIMS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.claims.capabilities_enabled=@('shared_project_registration')}
JsonCase 'registration mode advertised claim' 'P0-DIST-CLAIMS-001' 'contracts/distribution/registration-boundary.json' {param($c)$c.claims.registration_modes_advertised=@('shared_project_registration')}

JsonCase 'ADR-012 prematurely reverted to planned' 'P0-DIST-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.adrs|Where-Object{$_.id -eq 'ADR-012'}).status='planned'}
JsonCase 'ADR-013 prematurely accepted' 'P0-DIST-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.adrs|Where-Object{$_.id -eq 'ADR-013'}).status='accepted'}
JsonCase 'shared registration capability enabled in governance' 'P0-DIST-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.capabilities|Where-Object{$_.id -eq 'shared_project_registration'}).state='enabled'}
JsonCase 'gate marked passed in governance' 'P0-DIST-CROSS-CONTRACT-001' 'contracts/governance/capabilities.json' {param($c)($c.gates|Where-Object{$_.id -eq 'G-RELEASE'}).status='passed'}
JsonCase 'support matrix claims a supported row' 'P0-DIST-CROSS-CONTRACT-001' 'contracts/support/support-matrix.json' {param($c)$c.claim_state.supported_rows=@('shared_project_registration')}
JsonCase 'build skeleton claims graph transport runtime' 'P0-DIST-CROSS-CONTRACT-001' 'contracts/build-skeleton/skeleton.json' {param($c)$c.runtime_boundary.graph_transport=$true}
JsonCase 'build skeleton npm files widened' 'P0-DIST-ARTIFACTS-001' 'contracts/build-skeleton/skeleton.json' {param($c)$c.build_policy.npm_files=@('dist/index.js')}

TextCase 'ADR-001 registration wording removed' 'P0-DIST-CROSS-CONTRACT-001' 'docs/adr/ADR-001-runtime-and-self-hosting-boundary.md' {param($t)$t-replace'registration remains gated by ADR-012, publisher governance, signed','registration remains available on request'}
TextCase 'ADR-005 anti-rollback wording removed' 'P0-DIST-CROSS-CONTRACT-001' 'docs/adr/ADR-005-persistence-and-cryptography.md' {param($t)$t-replace'older binary refuses to write a newer schema or ciphertext version','older binary may still write a newer schema or ciphertext version'}
TextCase 'ADR-010 certificate cleanup wording removed' 'P0-DIST-CROSS-CONTRACT-001' 'docs/adr/ADR-010-add-in-bridge.md' {param($t)$t-replace'completely removed on disconnect and uninstall','left in place after disconnect and uninstall'}
TextCase 'ADR-PRIV-001 diagnostics wording removed' 'P0-DIST-CROSS-CONTRACT-001' 'docs/adr/ADR-PRIV-001-derived-metadata-and-source-boundary.md' {param($t)$t-replace'exact content-free schema plus ADR-012, G-PRIV, G-RELEASE, and G-SEC-AUDIT','exact content-free schema plus product-owner sign-off'}

TextCase 'spec contradiction appended' 'P0-DIST-INVENTORY-001' 'docs/product-spec.md' {param($t)$t+"`nContrary rule: the shared OpenLoops registration is enabled by default.`n"}
TextCase 'plan contradiction appended' 'P0-DIST-INVENTORY-001' 'docs/implementation-plan.md' {param($t)$t+"`nP0-WI-15 signs and publishes the first installer.`n"}
TextCase 'ADR contradiction appended' 'P0-DIST-CROSS-CONTRACT-001' 'docs/adr/ADR-012-distribution-and-registration.md' {param($t)$t+"`nContrary decision: a downgrade is permitted once the update metadata signature validates.`n"}
TextCase 'trace contradiction appended' 'P0-DIST-INVENTORY-001' 'docs/prd-traceability.md' {param($t)$t+"`nP0-WI-15 passed G-ID and G-RELEASE and ships the signed installer.`n"}
TextCase 'fresh checker preapproved' 'P0-DIST-FRESH-CHECKER-001' 'docs/prd-traceability.md' {param($t)$t-replace'\| P0-DIST-FRESH-CHECKER-001 \|([^\n]*)Passed at P0-WI-15 closure','| P0-DIST-FRESH-CHECKER-001 |$1Passed without independent review'}

if($script:fail.Count-gt 0){[Console]::Error.WriteLine(('FAIL: distribution and registration synthetic mutations: '+($script:fail-join'; ')));exit 1};Write-Output ('PASS: distribution and registration synthetic mutations ({0} rejection cases; OS temp only)' -f $script:count)
