[package]
name = "openloops-application"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
openloops-contracts = { path = "../openloops-contracts" }
openloops-domain = { path = "../openloops-domain" }
openloops-persistence = { path = "../openloops-persistence" }

[lints]
workspace = true
